pull_request_rules:
  - name: Automatic merge on approval and CI success
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=ci
      - base=main
    actions:
      merge:
        method: merge
